export interface StateCityMap {
  [state: string]: string[];
}

export const INDIAN_STATES_AND_CITIES: StateCityMap = {
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Prayagraj (Allahabad)",
    "Meerut",
    "Ghaziabad",
    "Noida",
    "Greater Noida",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Ayodhya",
    "Jhansi",
    "Mathura",
    "Vrindavan",
    "Muzaffarnagar",
    "Budaun",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad",
    "Maunath Bhanjan (Mau)",
    "Hapur",
    "Faizabad",
    "Etawah",
    "Mirzapur",
    "Bulandshahr",
    "Sambhal",
    "Amroha",
    "Hardoi",
    "Fatehpur",
    "Raebareli",
    "Orai",
    "Sitapur",
    "Bahraich",
    "Modinagar",
    "Unnao",
    "Jaunpur",
    "Lakhimpur Kheri",
    "Hathras",
    "Banda",
    "Pilibhit",
    "Barabanki",
    "Khurja",
    "Gonda",
    "Mainpuri",
    "Lalitpur",
    "Etah",
    "Deoria",
    "Ghazipur",
    "Sultanpur",
    "Azamgarh",
    "Bijnor",
    "Sahaswan",
    "Basti",
    "Chandausi",
    "Akbarpur",
    "Ballia",
    "Tanda",
    "Shikohabad",
    "Shamli",
    "Awagarh",
    "Kasganj",
    "Firozabad",
    "Baghpat",
    "Chitrakoot",
    "Amethi",
    "Sant Kabir Nagar",
    "Pratapgarh",
    "Kaushambi",
    "Bhadohi",
    "Maharajganj",
    "Sonbhadra",
    "Chandauli",
    "Balrampur",
    "Shravasti",
    "Ambedkar Nagar",
    "Kushinagar",
    "Hamirpur",
    "Mahoba",
    "Kannauj"
  ],
  "Maharashtra": [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Aurangabad (Chhatrapati Sambhajinagar)",
    "Navi Mumbai",
    "Solapur",
    "Mira-Bhayandar",
    "Bhiwandi",
    "Amravati",
    "Nanded",
    "Kolhapur",
    "Ulhasnagar",
    "Sangli",
    "Malegaon",
    "Jalgaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Ichalkaranji",
    "Jalana",
    "Ambarnath",
    "Bhusawal",
    "Panvel",
    "Badlapur",
    "Beed",
    "Gondia",
    "Satara",
    "Barshi",
    "Yavatmal",
    "Akhadapuram",
    "Osmanabad (Dharashiv)",
    "Nandurbar",
    "Wardha",
    "Udgir",
    "Hinganghat"
  ],
  "Delhi / NCR": [
    "New Delhi",
    "Central Delhi",
    "North Delhi",
    "South Delhi",
    "East Delhi",
    "West Delhi",
    "Rohini",
    "Dwarka",
    "Vasant Kunj",
    "Saket",
    "Karol Bagh",
    "Connaught Place",
    "Janakpuri",
    "Pitampura",
    "Shahdara",
    "Patparganj",
    "Lajpat Nagar",
    "Mayur Vihar",
    "Chanakyapuri",
    "Kalkaji",
    "Noida",
    "Gurgaon (Gurugram)",
    "Ghaziabad",
    "Faridabad"
  ],
  "Karnataka": [
    "Bengaluru (Bangalore)",
    "Mysore (Mysuru)",
    "Hubballi-Dharwad",
    "Mangaluru (Mangalore)",
    "Belagavi (Belgaum)",
    "Kalaburagi (Gulbarga)",
    "Davanagere",
    "Ballari (Bellary)",
    "Vijayapura (Bijapur)",
    "Shivamogga (Shimoga)",
    "Tumakuru (Tumkur)",
    "Raichur",
    "Bidar",
    "Hospet",
    "Hassan",
    "Gadag-Betageri",
    "Udupi",
    "Robertson Pet",
    "Bhadravati",
    "Chitradurga",
    "Kolar",
    "Mandya",
    "Chikkamagaluru",
    "Gangavati",
    "Bagalkot",
    "Ranebennuru"
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli (Trichy)",
    "Tiruppur",
    "Salem",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thoothukudi (Tuticorin)",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivakasi",
    "Karur",
    "Udhagamandalam (Ooty)",
    "Hosur",
    "Nagercoil",
    "Kanchipuram",
    "Kumarapalayam",
    "Karaikudi",
    "Neyveli",
    "Cuddalore",
    "Kumbakonam",
    "Tiruvannamalai",
    "Pollachi",
    "Rajapalayam",
    "Gudiyatham",
    "Pudukkottai",
    "Vaniyambadi",
    "Ambur",
    "Nagapattinam"
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Asansol",
    "Siliguri",
    "Durgapur",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Habra",
    "Kharagpur",
    "Shantipur",
    "Dankuni",
    "Dhulian",
    "Ranaghat",
    "Haldia",
    "Raiganj",
    "Krishnanagar",
    "Nabadwip",
    "Medinipur",
    "Jalpaiguri",
    "Balurghat",
    "Basirhat",
    "Bankura",
    "Chakdaha",
    "Darjeeling",
    "Alipurduar",
    "Purulia",
    "Kochi"
  ],
  "Gujarat": [
    "Ahmedabad",
    "Surat",
    "Vadodara (Baroda)",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Gandhidham",
    "Anand",
    "Navsari",
    "Morbi",
    "Nadiad",
    "Surendranagar",
    "Bharuch",
    "Mehsana",
    "Bhuj",
    "Porbandar",
    "Palanpur",
    "Valsad",
    "Vapi",
    "Gondal",
    "Veraval",
    "Godhra",
    "Patan",
    "Dahod",
    "Botad",
    "Amreli"
  ],
  "Telangana": [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Tadpatri",
    "Siddipet",
    "Jagtial",
    "Nirmal",
    "Kamareddy",
    "Kothagudem",
    "Bodhan",
    "Palwancha",
    "Mandamarri",
    "Koratla",
    "Sircilla",
    "Tandur",
    "Secunderabad"
  ],
  "Kerala": [
    "Thiruvananthapuram",
    "Kochi (Cochin)",
    "Kozhikode (Calicut)",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Alappuzha",
    "Kannur",
    "Kottayam",
    "Manjeri",
    "Thalassery",
    "Ponnani",
    "Vatakara",
    "Kanhangad",
    "Payyanur",
    "Koyilandy",
    "Parappanangadi",
    "Malappuram",
    "Pathanamthitta",
    "Cherthala",
    "Muvattupuzha",
    "Chavakkad",
    "Attingal"
  ],
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Kakinada",
    "Rajahmundry",
    "Kadapa",
    "Tirupati",
    "Anantapur",
    "Vizianagaram",
    "Eluru",
    "Ongole",
    "Nandyal",
    "Machilipatnam",
    "Adoni",
    "Tenali",
    "Chittoor",
    "Hindupur",
    "Proddatur",
    "Bhimavaram",
    "Madanapalle",
    "Guntakal",
    "Srikakulam",
    "Narasaraopet",
    "Tadepalligudem",
    "Tadpatri",
    "Bapatla"
  ],
  "Rajasthan": [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Sri Ganganagar",
    "Kishangarh",
    "Baran",
    "Dhaulpur",
    "Tonk",
    "Beawar",
    "Hanumangarh",
    "Chittorgarh",
    "Sawai Madhopur",
    "Churu",
    "Jhunjhunu",
    "Barmer",
    "Jaisalmer",
    "Bundi",
    "Nagaur",
    "Makrana"
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Murwara (Katni)",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Morena",
    "Bhind",
    "Chhindwara",
    "Guna",
    "Shivpuri",
    "Vidisha",
    "Chhatarpur",
    "Damoh",
    "Mandsaur",
    "Khargone",
    "Neemuch",
    "Pithampur",
    "Hoshangabad",
    "Itarsi",
    "Sehore"
  ],
  "Bihar": [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Bihar Sharif",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Danapur",
    "Saharsa",
    "Sasaram",
    "Hajipur",
    "Dehri-on-Sone",
    "Bettiah",
    "Motihari",
    "Bagaha",
    "Siwan",
    "Kishanganj",
    "Jamalpur",
    "Buxar",
    "Jehanabad",
    "Aurangabad",
    "Samastipur"
  ],
  "Punjab": [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Mohali (SAS Nagar)",
    "Batala",
    "Pathankot",
    "Moga",
    "Abohar",
    "Malerkotla",
    "Khanna",
    "Phagwara",
    "Muktsar",
    "Barnala",
    "Rajpura",
    "Firozpur",
    "Kapurthala",
    "Sunam",
    "Sangrur",
    "Fazilka",
    "Gurdaspur",
    "Faridkot"
  ],
  "Haryana": [
    "Faridabad",
    "Gurugram (Gurgaon)",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Bhiwani",
    "Sirsa",
    "Bahadurgarh",
    "Jind",
    "Thanesar (Kurukshetra)",
    "Kaithal",
    "Rewari",
    "Palwal",
    "Fatehabad",
    "Gohana",
    "Tohana",
    "Narwana"
  ],
  "Odisha (Orissa)": [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Brahmapur (Berhampur)",
    "Sambalpur",
    "Puri",
    "Balasore (Baleshwar)",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Jeypore",
    "Bargarh",
    "Rayagada",
    "Bhawanipatna",
    "Dhenkanal",
    "Barbil",
    "Kendujhar",
    "Balangir"
  ],
  "Jharkhand": [
    "Jamshedpur",
    "Dhanbad",
    "Ranchi",
    "Bokaro Steel City",
    "Deoghar",
    "Phusro",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar (Daltonganj)",
    "Chirkunda",
    "Chaibasa",
    "Dumka"
  ],
  "Chhattisgarh": [
    "Raipur",
    "Bhilai Nagar",
    "Bilaspur",
    "Korba",
    "Rajnandgaon",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Dhamtari",
    "Mahasamund",
    "Kanker",
    "Durg"
  ],
  "Assam": [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Dhubri",
    "Diphu",
    "North Lakhimpur",
    "Karimganj",
    "Sivasagar",
    "Golaghat"
  ],
  "Uttarakhand": [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani-Kathgodam",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Nainital",
    "Almora",
    "Pithoragarh",
    "Mussoorie",
    "Kotdwar",
    "Ramnagar",
    "Srinagar"
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Palampur",
    "Baddi",
    "Nahan",
    "Paonta Sahib",
    "Sundarnagar",
    "Chamba",
    "Una",
    "Kullu",
    "Hamirpur",
    "Bilaspur",
    "Dalhousie",
    "Manali"
  ],
  "Goa": [
    "Panaji (Panjim)",
    "Vasco da Gama",
    "Margao",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    "Cuncolim",
    "Valpoi",
    "Sanquelim",
    "Canacona"
  ],
  "Jammu & Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Sopore",
    "Kathua",
    "Udhampur",
    "Punch",
    "Rajouri",
    "Kupwara",
    "Pulwama",
    "Bandipora",
    "Kulgam",
    "Shopian"
  ],
  "Ladakh": [
    "Leh",
    "Kargil",
    "Diskit",
    "Padum",
    "Drass",
    "Khaltse"
  ],
  "Chandigarh": [
    "Chandigarh City",
    "Manimajra",
    "Kharar",
    "Panchkula Border",
    "Zirakpur Area"
  ],
  "Puducherry (Pondicherry)": [
    "Puducherry City",
    "Karaikal",
    "Yanam",
    "Mahe",
    "Ariyankuppam",
    "Villianur"
  ],
  "Tripura": [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Pratapgarh",
    "Kailasahar",
    "Belonia",
    "Khowai",
    "Ambassa"
  ],
  "Meghalaya": [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongpoh",
    "Baghmara",
    "Williamnagar"
  ],
  "Manipur": [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Churachandpur",
    "Ukhrul",
    "Kakching",
    "Senapati"
  ],
  "Nagaland": [
    "Dimapur",
    "Kohima",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Phek"
  ],
  "Mizoram": [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Champhai",
    "Kolasib",
    "Serchhip"
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Namsai",
    "Ziro",
    "Tawang",
    "Bomdila",
    "Along",
    "Roing"
  ],
  "Sikkim": [
    "Gangtok",
    "Namchi",
    "Gyalshing",
    "Singtam",
    "Rangpo",
    "Jorethang",
    "Mangan"
  ],
  "Andaman & Nicobar Islands": [
    "Port Blair",
    "Car Nicobar",
    "Diglipur",
    "Mayabunder",
    "Rangat",
    "Havelock Island (Swaraj Dweep)"
  ],
  "Dadra & Nagar Haveli and Daman & Diu": [
    "Silvassa",
    "Daman",
    "Diu",
    "Amli",
    "Bhitarpara"
  ],
  "Lakshadweep": [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kadmat"
  ]
};

export const COUNTRY_CODES = [
  { code: "+91", country: "IN (India)" },
  { code: "+1", country: "US/CA (North America)" },
  { code: "+44", country: "UK (United Kingdom)" },
  { code: "+61", country: "AU (Australia)" },
  { code: "+971", country: "AE (UAE)" },
  { code: "+65", country: "SG (Singapore)" },
  { code: "+966", country: "SA (Saudi Arabia)" },
  { code: "+974", country: "QA (Qatar)" },
  { code: "+965", country: "KW (Kuwait)" },
  { code: "+968", country: "OM (Oman)" },
  { code: "+973", country: "BH (Bahrain)" },
  { code: "+60", country: "MY (Malaysia)" },
  { code: "+64", country: "NZ (New Zealand)" },
  { code: "+49", country: "DE (Germany)" },
  { code: "+33", country: "FR (France)" },
  { code: "+31", country: "NL (Netherlands)" },
  { code: "+39", country: "IT (Italy)" },
  { code: "+34", country: "ES (Spain)" },
  { code: "+81", country: "JP (Japan)" },
  { code: "+82", country: "KR (South Korea)" },
  { code: "+27", country: "ZA (South Africa)" },
  { code: "+86", country: "CN (China)" },
  { code: "+852", country: "HK (Hong Kong)" },
  { code: "+886", country: "TW (Taiwan)" },
  { code: "+66", country: "TH (Thailand)" },
  { code: "+62", country: "ID (Indonesia)" },
  { code: "+63", country: "PH (Philippines)" },
  { code: "+880", country: "BD (Bangladesh)" },
  { code: "+977", country: "NP (Nepal)" },
  { code: "+94", country: "LK (Sri Lanka)" },
  { code: "+92", country: "PK (Pakistan)" },
  { code: "+20", country: "EG (Egypt)" },
  { code: "+234", country: "NG (Nigeria)" },
  { code: "+254", country: "KE (Kenya)" }
];
